//section15-exception.go
package main

import "fmt"

func main() {
	var a, b int = 10, 0

	result := a / b
	fmt.Println(result)
}
